# Staging and publishing profile for druid-website.git:

staging:
  profile: ~
  whoami:  asf-staging

publish:
  whoami:  asf-site

  
github:
  description: 'Apache Druid Website
  homepage: https://druid.apache.org/
